version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        python backend/manage.py migrate &&
        python backend/manage.py collectstatic --noinput &&
        uvicorn backend.config.asgi:application --host 0.0.0.0 --port 8011
      "
    volumes:
      - .:/app
    ports:
      - "8011:8011"
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/backend/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
